### ISSUE TITLE
Table columns not aligned after switching from XML view

### ISSUE THREAD

**Issue by asmigala** [elfilip/BQT_GUI#2]
Sometimes when clicking _Show as table_, the resulting table columns are not aligned properly. Usually happens right after selecting a scenario on the _Total Results_ tab
![screenshot from 2016-02-16 17-35-44](https://cloud.githubusercontent.com/assets/9480152/13083393/182c65e2-d4d5-11e5-8b1a-5dd36243e975.png)

**Comment by asmigala** [comment]
This is due to `<message-startswith>` tag not being recognized by the gui

**Comment by jdurani** [comment]
Resolved. Added support for message-contains, message-startswith and messageRegex

**Comment by asmigala** [comment]
Works ok now, thanks for the fix
